version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./chroma_db:/app/chroma_db
    environment:
      - UPLOAD_DIR=/app/uploads
      - PROCESSED_DIR=/app/processed
      - CHROMA_DB_DIR=/app/chroma_db
      - TESSERACT_PATH=/usr/bin/tesseract
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run app/frontend/main.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8000/api
    depends_on:
      - backend
    restart: unless-stopped 